services:
  mathhelper:
    container_name: mathhelper
    restart: unless-stopped
    build:
      context: ../MathHelper
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - mathhelper-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=DataSource=/app/data/MathHelper.db;Cache=Shared
      - ASPNETCORE_DATAPROTECTION_DIRECTORY=/app/data/keys

volumes:
  mathhelper-data:
